# Generated by Django 5.2.1 on 2025-07-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuing_organization', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(max_length=100)),
                ('verification_url', models.URLField()),
                ('description', models.TextField()),
                ('skills_validated', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('project', 'Project Inquiry'), ('collab', 'Collaboration Request'), ('tech', 'Technical Question'), ('networking', 'Professional Networking')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('about_me', models.TextField()),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('background', models.TextField()),
                ('interests', models.TextField()),
                ('philosophy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('key_features', models.TextField()),
                ('technologies', models.TextField()),
                ('live_url', models.URLField()),
                ('github_url', models.URLField()),
                ('timeline', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('competencies', models.TextField()),
                ('experience', models.TextField()),
                ('education', models.TextField()),
                ('certifications', models.TextField()),
                ('projects', models.TextField()),
                ('awards', models.TextField()),
                ('languages', models.TextField()),
                ('volunteer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('lang', 'Programming Languages'), ('frontend', 'Frontend Frameworks'), ('backend', 'Backend Technologies'), ('db', 'Database Technologies'), ('tools', 'Development Tools'), ('testing', 'Testing & QA'), ('design', 'Design & UI Tools'), ('soft', 'Professional Skills')], max_length=20)),
                ('competency_level', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skill_level', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('stackoverflow', 'Stack Overflow'), ('devto', 'Dev.to'), ('dribbble', 'Dribbble')], max_length=20)),
                ('url', models.URLField()),
                ('handle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('followers', models.PositiveIntegerField()),
                ('content_types', models.TextField()),
            ],
        ),
    ]
