# Generated by Django 5.2.5 on 2025-08-30 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_project_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon_class', models.CharField(help_text='FontAwesome class, e.g. fas fa-code', max_length=50)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_heading', models.CharField(default="Hi, I'm Gerard Ugwu", max_length=100)),
                ('hero_subtitle', models.TextField(default='Backend Developer • Python Enthusiast • ALX ProDev Learner • Web Developer\nCrafting modern, scalable, and responsive web applications…')),
                ('hero_cta_primary_text', models.CharField(default='View My Work', max_length=30)),
                ('hero_cta_primary_link', models.CharField(default='/projects', max_length=255, validators=[django.core.validators.URLValidator()])),
                ('hero_cta_secondary_text', models.CharField(default='Get In Touch', max_length=30)),
                ('hero_cta_secondary_link', models.CharField(default='/contact', max_length=255, validators=[django.core.validators.URLValidator()])),
                ('about_paragraphs', models.JSONField(default=list, help_text='Enter each paragraph as a list item in the admin.')),
                ('featured_projects_blurb', models.TextField(default='My portfolio showcases e-commerce platforms, SaaS dashboards & automation tools…')),
                ('featured_projects_cta_text', models.CharField(default='Explore All Projects', max_length=30)),
                ('featured_projects_cta_link', models.CharField(default='/projects', max_length=255, validators=[django.core.validators.URLValidator()])),
            ],
            options={
                'verbose_name': 'Site Profile',
            },
        ),
    ]
