# Generated by Django 5.2.5 on 2025-09-01 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_profile_background_remove_profile_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProfileDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_type', models.CharField(choices=[('location', 'Location'), ('email', 'Email'), ('phone', 'Phone'), ('experience', 'Experience')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('icon_class', models.CharField(default='fas fa-circle', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='myapp.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
