# Generated by Django 5.2.5 on 2025-09-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_profile_experience_years_profiledetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(default='My technical expertise spans the full web development stack…')),
            ],
            options={
                'verbose_name_plural': 'Skill Summary',
            },
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'order']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='competency_level',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_level',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(default='fab fa-code', help_text="FontAwesome class, e.g. 'fab fa-js'", max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='skill',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated list of tags'),
        ),
        migrations.AddField(
            model_name='skill',
            name='title',
            field=models.CharField(default='Programming Languages', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('LANGUAGE', 'Programming Languages'), ('FRONTEND', 'Frontend Frameworks'), ('BACKEND', 'Backend Technologies'), ('DATABASE', 'Database Technologies'), ('DEVOPS', 'Development Tools'), ('TESTING', 'Testing & QA'), ('DESIGN', 'Design & UI Tools'), ('SOFT', 'Professional Skills'), ('SUMMARY', 'Skills Summary')], max_length=20),
        ),
    ]
