# Generated by Django 5.2.5 on 2025-09-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_skillsummary_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completion_date', models.DateField()),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fas fa-laptop-code', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='credential_id',
            new_name='issuer',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='expiration_date',
            new_name='valid_until',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='issuing_organization',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='skills_validated',
        ),
        migrations.AddField(
            model_name='certificate',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('cloud', 'Cloud & DevOps'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('security', 'Security')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='verification_url',
            field=models.URLField(blank=True),
        ),
    ]
