# Generated by Django 5.2.5 on 2025-09-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_learningpath_rename_credential_id_certificate_issuer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_class', models.CharField(max_length=40)),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('professional', 'Professional Networks'), ('social', 'Social Media'), ('additional', 'Additional Platforms')], max_length=15)),
                ('followers', models.CharField(blank=True, max_length=20)),
                ('posts', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('highlights', models.TextField(help_text='Bullet list, one line per bullet')),
                ('popular', models.TextField(help_text='Popular items, one line per item')),
            ],
        ),
    ]
