# Generated by Django 5.2.5 on 2025-10-01 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_socialplatform'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.EmailField(default='kachimaxy1@gmail.com', max_length=254)),
                ('best_for', models.TextField()),
                ('response_time', models.CharField(default='Within 48 hours', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GuidelineSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon_html', models.TextField(help_text='FontAwesome/SVG HTML for icon')),
                ('label', models.CharField(default='Contact', max_length=100)),
                ('link', models.URLField(blank=True, null=True)),
                ('display', models.CharField(blank=True, max_length=200, null=True)),
                ('best_for', models.TextField()),
                ('availability', models.CharField(blank=True, max_length=200, null=True)),
                ('target_blank', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('points', models.TextField(help_text='Use line breaks for multiple points')),
            ],
        ),
        migrations.CreateModel(
            name='GuidelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.guidelinesection')),
            ],
        ),
    ]
