# Generated by Django 5.2.5 on 2025-10-01 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_emailaddress_emailtemplates_faq_guidelinesection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon_html', models.TextField(default='<i class="fas fa-envelope"></i>', help_text='HTML for the icon (Font Awesome, SVG, etc.)')),
                ('label', models.CharField(default='Contact', max_length=100)),
                ('display', models.CharField(blank=True, help_text='Display text for the contact method', max_length=200)),
                ('link', models.URLField(blank=True, help_text='URL for the contact method')),
                ('target_blank', models.BooleanField(default=True, help_text='Open in new tab')),
                ('best_for', models.TextField()),
                ('availability', models.CharField(default='Monday-Friday, 9 AM - 6 PM', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EmailGuidelineSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GuidelineSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='myapp.emailguidelinesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SecurityPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubsectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.guidelinesubsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WatermarkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=512)),
                ('ip_address', models.CharField(max_length=64)),
                ('user_email', models.CharField(blank=True, max_length=254, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watermark Record',
                'verbose_name_plural': 'Watermark Records',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Method',
        ),
        migrations.AlterModelOptions(
            name='emailaddress',
            options={'ordering': ['order', 'title'], 'verbose_name_plural': 'Email addresses'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplates',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order', 'question'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='guidelineitem',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='securityitem',
            options={'ordering': ['order', 'title']},
        ),
        migrations.RenameField(
            model_name='guidelineitem',
            old_name='text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='securityitem',
            name='points',
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailtemplates',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailtemplates',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guidelineitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='securityitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='securityitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='best_for',
            field=models.TextField(help_text='What this email is best suited for'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='emailtemplates',
            name='key',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='emailtemplates',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtemplates',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='guidelineitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.emailguidelinesection'),
        ),
        migrations.AddField(
            model_name='securitypoint',
            name='security_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='myapp.securityitem'),
        ),
        migrations.DeleteModel(
            name='GuidelineSection',
        ),
    ]
