# Generated by Django 5.2.5 on 2025-10-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_screenshotevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshotevent',
            old_name='event_time',
            new_name='created_at',
        ),
    ]
