# Generated by Django 5.2.5 on 2025-10-02 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_event_time_screenshotevent_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screenshotevent',
            options={'ordering': ['-event_time'], 'verbose_name': 'Screenshot Event', 'verbose_name_plural': 'Screenshot Events'},
        ),
        migrations.RemoveField(
            model_name='watermarkrecord',
            name='created_at',
        ),
        migrations.AddField(
            model_name='screenshotevent',
            name='event_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='watermarkrecord',
            name='event_type',
            field=models.CharField(choices=[('screenshot', 'Screenshot'), ('print', 'Print'), ('copy', 'Copy Attempt')], default='screenshot', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='screenshotevent',
            name='ip_address',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='screenshotevent',
            name='path',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='screenshotevent',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
