# Generated by Django 5.2.5 on 2025-10-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_screenshotevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReplyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Auto-Reply', max_length=100)),
                ('subject', models.CharField(default='Thank you for your message', max_length=200)),
                ('message', models.TextField(default="Hello {name},\n\nThank you for reaching out! I've received your message and will get back to you within 24 hours.\n\nHere's a copy of your message:\nSubject: {subject}\nMessage: {message}\n\nBest regards,\nGerard Ugwu\nBackend Developer")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
