# Generated by Django 5.2.5 on 2025-10-25 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_autoreplytemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watermarkrecord',
            options={},
        ),
        migrations.RemoveField(
            model_name='watermarkrecord',
            name='user_email',
        ),
        migrations.AddField(
            model_name='watermarkrecord',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watermarkrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watermarkrecord',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watermarkrecord',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watermarkrecord',
            name='event_type',
            field=models.CharField(choices=[('screenshot', 'Screenshot'), ('print_attempt', 'Print Attempt'), ('devtools_opened', 'DevTools Opened'), ('contextmenu_attempt', 'Right Click Attempt'), ('mobile_screenshot', 'Mobile Screenshot/Tab Switch'), ('location_update', 'Location Update')], max_length=50),
        ),
        migrations.AlterField(
            model_name='watermarkrecord',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watermarkrecord',
            name='path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='watermarkrecord',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
